name: evo_dask
channels:
- conda-forge
- default
dependencies:
- python=3.6.10
- pandas=0.23.3
- numpy=1.19.5
- scipy=1.4.1
- seaborn=0.11.2
- matplotlib=3.3.4
- statsmodels=0.9.0
- psutil=5.6.1
- dask=1.1.5