# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-64/ca-certificates-2022.3.29-hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/jpeg-9d-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libcxx-12.0.0-h2f01273_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libwebp-base-1.2.2-hca72f7f_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/llvm-openmp-12.0.0-h0dcd299_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/ncurses-6.3-hca72f7f_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/xz-5.2.5-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/yaml-0.2.5-haf1e3a3_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zlib-1.2.12-h4dc903c_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libffi-3.2.1-h0a44026_1007.conda
https://conda.anaconda.org/conda-forge/osx-64/libgfortran4-7.5.0-h1a10cd1_23.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/libpng-1.6.37-ha441bb4_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/lz4-c-1.9.3-h23ab428_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/openssl-1.1.1n-hca72f7f_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/readline-8.1.2-hca72f7f_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/tk-8.6.11-h7bc2e8c_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/freetype-2.11.0-hd8bbffd_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libgfortran-4.0.0-7_5_0_h1a10cd1_23.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/sqlite-3.38.2-h707629a_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zstd-1.4.9-h322a384_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libopenblas-0.3.12-openmp_h63d9170_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/libtiff-4.2.0-h87d7836_0.conda
https://conda.anaconda.org/conda-forge/osx-64/python-3.6.10-h4334963_1011_cpython.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/certifi-2021.5.30-py36hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/click-8.0.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cloudpickle-2.0.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cycler-0.11.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/dask-core-1.1.4-py36_1.conda
https://repo.anaconda.com/pkgs/main/noarch/heapdict-1.0.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/kiwisolver-1.3.1-py36h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/lcms2-2.12-hf1fd2bf_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libblas-3.9.0-8_openblas.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/locket-0.2.1-py36hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/markupsafe-2.0.1-py36h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/msgpack-python-1.0.2-py36hf7b0b51_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/olefile-0.46-py36_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/openjpeg-2.4.0-h66ea3da_0.conda
https://conda.anaconda.org/conda-forge/osx-64/psutil-5.6.1-py36h1de35cc_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-3.0.4-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/osx-64/python_abi-3.6-2_cp36m.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pytz-2021.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pyyaml-5.4.1-py36h9ed2024_1.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/sortedcontainers-2.4.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tblib-1.7.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/toolz-0.11.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/tornado-6.1-py36h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/noarch/typing_extensions-4.1.1-pyh06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.37.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/cytoolz-0.11.0-py36haf1e3a3_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jinja2-3.0.3-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libcblas-3.9.0-8_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/liblapack-3.9.0-8_openblas.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/packaging-21.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/partd-1.2.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/pillow-8.3.1-py36ha4cf6ea_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/setuptools-58.0.4-py36hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/zict-2.0.0-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/distributed-1.28.1-py36_0.conda
https://conda.anaconda.org/conda-forge/osx-64/numpy-1.19.5-py36h08b5fde_2.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pip-21.2.2-py36hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/bokeh-2.3.2-py36hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/matplotlib-base-3.3.4-py36h8b3ea08_0.conda
https://conda.anaconda.org/conda-forge/osx-64/pandas-0.23.3-py36hf8a1672_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/scipy-1.4.1-py36h1dac7e4_3.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/dask-1.1.4-py36_1.conda
https://conda.anaconda.org/conda-forge/osx-64/matplotlib-3.3.4-py36h79c6626_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/patsy-0.5.1-py36_0.conda
https://conda.anaconda.org/conda-forge/noarch/seaborn-base-0.11.2-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/statsmodels-0.9.0-py36h917ab60_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/seaborn-0.11.2-hd8ed1ab_0.tar.bz2
